# Generated by Django 4.1.7 on 2023-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('plan_name', models.CharField(choices=[(1, 'Arcade'), (2, 'Advanced'), (3, 'Pro')], max_length=10)),
                ('plan_duration_is_monthly', models.BooleanField()),
                ('online_service', models.BooleanField()),
                ('larger_storage', models.BooleanField()),
                ('customizable_profile', models.BooleanField()),
            ],
        ),
    ]
