# Generated by Django 4.1.7 on 2023-04-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='customizable_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='larger_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='online_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_duration_is_monthly',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(choices=[(1, 'Arcade'), (2, 'Advanced'), (3, 'Pro')], default=1, max_length=10),
        ),
    ]
