# Generated by Django 4.1.7 on 2023-04-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_details', '0002_alter_plan_customizable_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='total_cost',
            field=models.IntegerField(default=9),
        ),
    ]
